### ISSUE TITLE
Implement Suggested Add-Ons for experiment

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11950]
This tracking issue covers the work that needs to be done to implement the Suggested Add-Ons experiment.

- [x] [Implement suggestions reducer and saga](https://github.com/mozilla/addons-frontend/issues/11951)
- [x] [Update LandingAddonsCard to support the experiment](https://github.com/mozilla/addons-frontend/issues/11953)
- [x] [Send a GA event when a trusted add-on is installed](https://github.com/mozilla/addons-frontend/issues/11955)
- [x] [Implement an AddonSuggestions component and display it via an experiment](https://github.com/mozilla/addons-frontend/issues/11959)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-183)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-183
