### ISSUE TITLE
Mobile Pages Release Checklist

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1801]
Adding a set of checkboxes to cover off prior to release. Feel free to add to to the list any important things we should check/ensure prior to release of the mobile site.

Primary focus is adding things that won't necessarily fall under QA but overlap won't hurt.

* [x] Check CSP (look for warnings/violations) and review directives.
* [x] Check analytics enabled.
* [x] Check mobile cookie and user-agent.
* [x] Check translations + locales.
* [x] Make sure Sentry is hooked up for error reporting. (#1559)

**Comment by kumar303** [comment]
I think we can close this, right?

**Comment by muffinresearch** [comment]
Yes we can
