### ISSUE TITLE
Create desktop versions of existing mobile pages

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2296]
Basically the plan for Q2 is to implement a desktop version (from the mocks) for every currently implemented mobile page. This will likely also include a user page (which we'll need to implement on mobile as well), but for now we'll stick to the scope as being all existing mobile pages. This is my Q2 goal ^_^

This will be the tracker bug for that because I like tracker bugs because I've worked here too long. 😜

I'll create individual issues for these things in due time, possibly tonight but maybe later.

* [x] implement a desktop header #2436
* [x] implement a desktop extension details page #2430
* [x] implement a desktop theme details page #2559
* [x] implement a desktop search page #2560
* [x] implement a desktop categories page #2563
* [x] implement a desktop extensions landing page #2561
* [x] implement a desktop themes landing page #2562
* [x] <strike>implement a desktop "all reviews" page #2564</strike>
* [x] implement a desktop home page #2565
* [x] implement a desktop footer #2518

**Comment by tofumatt** [comment]
Woohoo! 🎉
