### ISSUE TITLE
[tracker] Clean up as much of the test warnings as possible

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2448]
There's a few things to complete this:

* [x] Fix sinon deprecation warnings #2479
* [ ] Fix warnings about incorrect props
* [x] Fix React deprecation warnings re: proptypes by using the split out package #2475
* [x] Move to react-router 4 (since I think some of the deprecations come from there).

There's probably others too.

**Comment by willdurand** [comment]
A lot of warnings have been removed thanks to #5652

**Comment by willdurand** [comment]
It should be improved when #5826 gets merged since I disabled the logging layer in the "test" environment.

**Comment by willdurand** [comment]
so this has been mostly fixed but now that #2980 has been fixed, I don't think we should be doing anything anymore.
