### ISSUE TITLE
[tracker] Add specialised 404 states for add-ons

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2769]
This could become a tracker bug if we want to spin these out into their own issues/PRs, which we probably do. But for now, we need to handle:

- [ ] Disabled by developer (Only show a notice. Show edit, review, and admin links for users with permissions.) https://github.com/mozilla/addons-frontend/issues/2261
- [ ] Disabled by admin (Current mobile pages show a “Not Authorized” error. Only show a notice. Show edit, review, and admin links for users with permissions) https://github.com/mozilla/addons-frontend/issues/2261
- [x] Add-on doesn’t exist / was deleted (already handled)
- [ ] Add-on pending review with no approved versions (Handle like “doesn’t exist” case except for developers)
- [x] Handle 403s as 404 on Add-on Detail and Add-on "All Reviews" pages (#3218)

**Comment by willdurand** [comment]
We have changed the 404 messages already, so this is outdated.
