### ISSUE TITLE
[tracker] User Profiles

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2781]
Create a page that allows the user to edit their profile:

 - [x] ~~Add users reducers/sagas #4030~~
 - [x] Add user profile view #2749 
 - [x] Add profile editing (AKA Account Settings) #3144

See [this document](https://docs.google.com/document/d/1cJ1k8HsAb6taauvJMDLOiYMa1McfUXNgEtax3hoToPc/edit#heading=h.zbgeax3cwqnz) for a break down of all user profile features.

**Comment by kumar303** [comment]
Everything in this tracker has been nominated for MVP removal so I'm nominating the tracker.

**Comment by muffinresearch** [comment]
Reviewed and removed from the MVP.

**Comment by muffinresearch** [comment]
Refs: #3761

**Comment by willdurand** [comment]
Closing this issue. I will open a new "tracker" issue for the edit page.
