### ISSUE TITLE
[tracker] Collections feature

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2782]
**The collections feature is being tracked in [this project](https://github.com/mozilla/addons-frontend/projects/3?fullscreen=true)**

Docs / specs:

- [Collections features that we are implementing](https://docs.google.com/document/d/1cJ1k8HsAb6taauvJMDLOiYMa1McfUXNgEtax3hoToPc/edit#heading=h.z5wk3ws26iay)
- [Overview of simplified Collections](https://docs.google.com/document/d/1DutmS8yco-hNiKJ1-0MrkAkze7Ue88xpA4b-MWx6MLI/edit#)

See the following links for the separate issues.

**2017 Q3**

- [x] ~~Collection View #3140 (MVP)~~
- [x] ~~Link to edit your collection while signed in~~ https://github.com/mozilla/addons-frontend/issues/3766

**2017 Q4**
- *landed platform work needed for 2018 Q1 features*

**2018 Q1**

- [x] ~~Add an add-on to an existing collection~~ #2768
- [x] ~~Edit collection name, description, URL~~ https://github.com/mozilla/addons-frontend/issues/4002
- [ ] Edit the add-ons in a collection https://github.com/mozilla/addons-frontend/issues/4004
- [ ] Create a new collection https://github.com/mozilla/addons-frontend/issues/4003
- [ ] List my collections and edit / delete / add #3142 
- [ ] Add an add-on to a new collection https://github.com/mozilla/addons-frontend/issues/3993

**Future?**

- [ ] Delete a collection https://github.com/mozilla/addons-frontend/issues/4195
- [ ] Allow contributors to maintain a collection https://github.com/mozilla/addons-frontend/issues/4000
- [ ] Show Collection comments https://github.com/mozilla/addons-frontend/issues/3890
- [ ] Sort add-ons in a collection https://github.com/mozilla/addons-frontend/issues/3991
- [ ] Install an add-on from a collection https://github.com/mozilla/addons-frontend/issues/3992
- [ ] On detail page: this add-on is featured in `<Collection>` https://github.com/mozilla/addons-frontend/issues/3994

**Comment by kumar303** [comment]
The [goal of reduced discoverability](https://docs.google.com/document/d/1DutmS8yco-hNiKJ1-0MrkAkze7Ue88xpA4b-MWx6MLI/edit) for the new Collection feature makes me think we could do an MVP release without it (and just serve links from the old site). To do so, we would probably want to not feature any collections on the home page. Thoughts?

**Comment by tofumatt** [comment]
Works for me!

Matthew Riley MacPherson (sent from mobile)

**Comment by muffinresearch** [comment]
> The goal of reduced discoverability for the new Collections feature makes me think we could do an MVP release without it (and just serve links from the old site). To do so, we would probably want to not feature any collections on the home page. Thoughts?

Currently editorial want to feature content in collection and it's one of the few tools they have to curate content. So I think we just need to provide a collections view - everything else will be ok to be post-release.

**Comment by devaneymoz** [comment]
To confirm - Editorial requires collections to not only feature content on AMO itself, but collections are an integral part of existing marketing channels, such as the lifecycle email markeitng, where Firefox users, depending on their lifecycle stage, will automatically receive emails pointing to various curated collections on AMO.

**Comment by muffinresearch** [comment]
Refs: #3761

**Comment by bobsilverberg** [comment]
I don't think we need this issue anymore. Do you agree @kumar303?

**Comment by kumar303** [comment]
Agreed! See https://github.com/mozilla/addons-frontend/projects/3
