### ISSUE TITLE
[tracker]: Update styles across site to be in-line with most recent mocks/Photon update

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3398]
Many of the site components are before some of the photon styles or the newest mocks. Things like buttons have the wrong colour (which is why they have text-shadow–it was to make the text legible as the contrast of the previous colours was too low, see #2461), the card styles are a bit out-of-date, etc.

This issue can serve as the tracker for updating all the visual elements on the site that don't match the mocks. Feel free to file separate issues for each item, especially if/as you start working on them, but adding them here is a fine start.

### Updates needed

- [x] Update button styles (colours to match Photon colours and remove text shadow)
- [ ] Update Card ("shelf") component styles (border-radius, padding, etc.)
- [ ] Change Install Switch to "Add to Firefox" button (#3557/#TBD for improvements to button)
- [ ] Make sure as many colours use Photon as possible

Feel free to add to this list if you think of anything else 😄

**Comment by muffinresearch** [comment]
> Change Install Switch to "Add to Firefox" button

This is also subject to the outcome of user testing and some discussion around making sure all the relevant states can be reflected.

**Comment by willdurand** [comment]
There is a new redesign in the pipe, so let's close this issue.
