### ISSUE TITLE
Implement A/B test for TAAR Lite 

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4865]
Project: https://github.com/mozilla/addons-frontend/projects/5
Requirements doc: https://docs.google.com/document/d/1LoXn6a2QY2VrK3YobbreFXUTtYCc28iCH-qiWKwf7yU/edit?ts=5accb63a

Add a component to the add-on details page which displays recommendations driven by TAAR Lite. For the A/B test, users will be divided into 2 cohorts, one will receive recommendations based on the add-on they are currently viewing, while the other will receive a standard set of 4 recommended add-ons. Note that if the TAAR Lite service is unable to find recommendations for the add-on in question within a set timeframe, it will return the same set of 4 recommended add-ons, which are referred to as the fallback set.

In order to implement this we'll need to do the following:

- [ ] Implement API, saga and reducer code to interact with TAAR Lite endpoint. https://github.com/mozilla/addons-frontend/issues/4867
  - [ ] Update API code to call the TAAR Lite endpoint, which will be [provided by addons-server](https://github.com/mozilla/addons-server/issues/8118).
  - [ ] Update saga code to dispatch the API request and load the results into state.
  - [ ] Update reducer code to introduce actions for retrieving and loading TAAR Lite results.
- [ ] Create a POC component that can send different GA pings depending on a user's cohort, driven by react-ab. This will include code to read and set a cookie to maintain the cohort for a user. https://github.com/mozilla/addons-frontend/issues/4866
  - [ ] Implement a config flag which can be used to turn the experiment on and off.
- [ ] Update the component from https://github.com/mozilla/addons-frontend/issues/4866 display the TAAR Lite results.

**Comment by muffinresearch** [comment]
@bobsilverberg can this be closed in favour of the project or is there anything here that is missing from the project?

**Comment by bobsilverberg** [comment]
This can be closed. It's convenient to have a link to the doc here, so maybe it makes sense for a project to have one tracker issue in which we record things like that? Just something to consider.
