### ISSUE TITLE
upgrade api from v3 to v4

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#5527]
upgrade api from v3 to v4

---

- [x] 2018-05-18: renamed /reviews/ endpoint to /ratings/ https://github.com/mozilla/addons-server/issues/6849
- [x] 2018-05-25: renamed rating.rating property to rating.score https://github.com/mozilla/addons-server/pull/8332
- [x] 2018-06-05: dropped rating.title property https://github.com/mozilla/addons-server/issues/8144
- [x] 2018-07-12: added type property to autocomplete API. This change was also backported to the v3 API. https://github.com/mozilla/addons-server/issues/8803
- ~~2018-07-19: localised field values are always returned as objects, even if only a single language is requested. Setting a localised value with a string is removed too - it must always be an object of one or more translations. https://github.com/mozilla/addons-server/issues/8794~~
- [x] 2018-07-18: added previews property to discovery API addons object. This change was also backported to the v3 API. https://github.com/mozilla/addons-server/issues/8863
- [x] 2018-07-20: dropped downloads property from the collection add-ons results. https://github.com/mozilla/addons-server/issues/8944
- [x] 2018-08-16: added is_developer_reply property to ratings. This changed was also backported to the v3 API. https://github.com/mozilla/addons-server/issues/8993
- [x] 2018-09-13: added name and icon_url properties to the addon object in ratings. This changed was also backported to the v3 API. https://github.com/mozilla/addons-server/issues/9357
- [x] 2018-09-27: backed out “localised field values are always returned as objects” change from 2018-07-19 from v4 API. This is intended to be temporary change while addons-frontend upgrades. On addons-dev and addons stage enviroments the previous behavior is available as api/v4dev. The v4dev api is not available on AMO production server. https://github.com/mozilla/addons-server/issues/9467

**Comment by kumar303** [comment]
We need to do this. Today, when new features land in the API they have to be *backported* to v3 if we want to use them. This is unsustainable.

The v4 changelog is a fairly small list: https://addons-server.readthedocs.io/en/latest/topics/api/overview.html#v4-api-changelog

We should implement the ability to downgrade a single endpoint to v3 in case any hard to fix bug comes up.

Also, related: https://github.com/mozilla/addons-server/issues/8899

**Comment by willdurand** [comment]
Most new features have been backported and BC breaks are relatively easy, except this one:

> 2018-07-19: localised field values are always returned as objects, even if only a single language is requested. Setting a localised value with a string is removed too - it must always be an object of one or more translations. https://github.com/mozilla/addons-server/issues/8794

which is huge!

**Comment by willdurand** [comment]
https://github.com/mozilla/addons-frontend/pull/6142 allows to pass a API version to `callApi()` (and adds a config parameter named `apiVersion`).

**Comment by eviljeff** [comment]
@willdurand now mozilla/addons-server#9467 has landed `/v4/` now doesn't include the `localised field values are always returned as objects` change.

**Comment by willdurand** [comment]
I filed another issue for the new localized fields: https://github.com/mozilla/addons-frontend/issues/6422.

**Comment by willdurand** [comment]
For QA: please make sure AMO behaves as usual, especially reviews/ratings should continue to work (read, write, update, delete)

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO stage - FF62(win10&Android 8.0)
The release test results are [here](https://testrail.stage.mozaws.net/index.php?/plans/view/12783)
