### ISSUE TITLE
ERRORS using Add-On Collections:  Create, View, Edit, or Adding to 

### ISSUE THREAD

**Issue by SoSaysSunny** [mozilla/addons-frontend#7720]
### Describe the problem and steps to reproduce it:

Lots of issues with Collections.

VIEW / EDIT:
- When looking at the My Collections page, the number of add-ons in [my existing collection](https://addons.mozilla.org/en-US/firefox/collections/12774996/favorites/) is sometimes 12 and sometimes 55.
- When I view the collection, there are sometimes 12 or 55, not always the same as on the previous My Collections page.  Trying to go to the 2nd or 3rd page (if available) gives the Oops Error page.  Sorting by name always lowers the number to 12.
- I thought perhaps this was because most were the old style extension.

ADD:
- So I thought I'd add the ones that weren't among the 12.  I tried, unsuccessfully, to add them from the add-on pages but the number didn't increase (still either 12 or 55) and they didn't show up in the list (though default sort is newest on top).

CREATE:
- So I tried to create a new collection.  But when I tried to save the name/description, I got the Oops Error again (no matter what name I gave it).

ACK!

### What happened?
I get the error message:
> Oops! We can’t find that page
> 
> If you’ve followed a link from another site for an extension or theme, that item is no longer available. This could be because: [ ... ]
### Anything else we should know?
Have they stopped supporting Collections?  If so, this is annoying because I can't use CLEO to package the add-ons for friends and family.

**Comment by muffinresearch** [comment]
@bobsilverberg when you have a moment please could you take a look at and triage this?

**Comment by bobsilverberg** [comment]
This is odd. When I go to https://addons.mozilla.org/en-US/firefox/collections/12774996/favorites/, the page does not load and I get a message "You do not have permission to perform this action." That seems to be happening during server side rendering, so there is no information in the console or network tab about what is causing that error.

@kumar303 | @willdurand Can you reproduce that too?

<img width="1559" alt="Screenshot 2019-03-29 12 40 27" src="https://user-images.githubusercontent.com/142755/55248301-e327a200-521f-11e9-89b8-c15aa3ee2677.png">

**Comment by kumar303** [comment]
> Can you reproduce that too?

@bobsilverberg Yes, this error you saw is expected. The URL is a collection belonging to user ID 12774996 -- no one else can access it. This collection is named `favorites` which is a special type of collection that exists for historic reasons. It may be triggering special code. 

> ...I tried to create a new collection. But when I tried to save the name/description, I got the Oops Error again (no matter what name I gave it).

@SoSaysSunny sorry you're having trouble. For the record, I was able to create a new collection in the latest Firefox and save a couple add-ons to it without an error. I'm not sure why your user account is triggering errors.

What browser and version are you using?

**Comment by SoSaysSunny** [comment]
@kumar303 & @bobsilverberg,

Sorry for the delayed response ... It was nearly 2 weeks before anyone answered my post so I stopped checking all the time.

### ANSWER
I'm using **Firefox Quantum 60.6.1 ESR** on **Windows 7 Professional**.  _My senior citizen mom (and I) can't stand all the constant changes._

### UPDATE
Trying it just now ... 

![Collections](https://user-images.githubusercontent.com/48607777/55417566-8f29ff80-5536-11e9-805a-cf60829400ce.png)
* On the Collections page, it says The Sunny Set Up collection has 69 add-ons but the editing page says 26.
* It did allow me to go to the second page of the list of 26.
* It did allow me to add & delete items.
* It did allow me to see & edit another collection ([SoSaysSunny 2019](https://addons.mozilla.org/en-US/firefox/collections/12774996/SoSaysSunny-2019/)).

### TASKS / REQUESTS

- [ ] How do I **make a collection public**?  I didn't see a way ... If it's there it's not easy to find.  My main purpose in making this collection is to share all the add-ons I use with friends and family (since CLEO isn't around any more).

- [ ] **Collection add-on link errors** ... `?src=collection` is appended to the add-on links ([example](https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/?src=collection)) ... which sometimes don't work, giving the message `An unexpected error occurred` (I wish I'd gotten a screen shot before I reloaded the tab).

### ALSO

- [ ] If you have a means of giving **feedback / suggestions to AMO**:
* Ease of making collections public.
* Copy existing collection to make a similar but different one.
* Add a link back to My Collections from the Collection page (or to Other Collections By This User, if not the owner).
* It would be nice to be able to sort a collection by note or by custom order.
* Way to search for the old-style add-ons ... which I knew were still there from bookmarks but now seem to be gone ... so now I can't contact the developers to ask if they're working on updated add-ons. ... *sigh*
* Could we create a Security-, Stability-, & Speed-ONLY channel?  I can't be the only in-house tech support person for a Baby Boomer who doesn't want things changed all the time. 
* Are we ever going to get additional toolbars?  I used to have them on every edge of the screen:

![toolbars_2018-04-16](https://user-images.githubusercontent.com/48607777/55418810-0bbddd80-5539-11e9-84e5-9fd1e21e57a6.png)

- [ ] Do you happen to know of a **replacement for FireFTP**?  Nothing came up for "ftp" on AMO.  What about separate programs you would recommend?  Losing this has seriously hampered my website management ([SoSaysSunny.com](http://SoSaysSunny.com) and others).

Thanks!
  ~ Sunny

**Comment by kumar303** [comment]
Thanks for all the additional info! It's possible that we have a regression in Firefox ESR but we do aim to support it.

> How do I make a collection public?

Collections are already public. To share a collection first click on it to view all add-ons (not in edit mode). You can now copy and paste this URL, send it to someone, and they will be able to see the collection.

**Comment by SoSaysSunny** [comment]
@kumar303 

> It's possible that we have a regression in Firefox ESR but we do aim to support it.

I'm not sure what you're saying here.  If you're saying that ESR is a Security-, Stability-, & Speed-ONLY version: The problem is that it's geared toward institutions and so most senior citizens (even their kids) wouldn't know that ESR could be a solution.  The senior / Baby Boomer demographic is not a small group so this reason to choose ESR should be highlighted to be easier to find.

> > How do I make a collection public?
> 
> Collections are already public. To share a collection first click on it to view all add-ons (not in edit mode). You can now copy and paste this URL, send it to someone, and they will be able to see the collection.

Glad to know this.  I was confused by your prior post:

>  The URL is a collection belonging to user ID 12774996 -- no one else can access it. This collection is named `favorites` which is a special type of collection that exists for historic reasons. It may be triggering special code.

I tried to change the URL of that collection from "favorites" twice but it didn't work.

**Comment by kumar303** [comment]
> > It's possible that we have a regression in Firefox ESR but we do aim to support it.
> 
> I'm not sure what you're saying here. 

I was just saying that since Firefox ESR is an older version of Firefox, the addons.mozilla.org site may not be working correctly in it. If this is true, it's a bug. 

Can you try in the release version of Firefox just to see if it works there? https://www.mozilla.org/en-US/firefox/new/

I understand that ultimately you'd prefer to use Firefox ESR.

> > Collections are already public...
> 
> Glad to know this. I was confused by your prior post:
> 
> > The URL is a collection belonging to user ID 12774996 -- no one else can access it. This collection is named `favorites` which is a special type of collection that exists for historic reasons...

Oh, right! I forgot that the special "favorites" collection is not public. This is confusing. The only way you could make it public would be to create a new collection and re-add all of your extensions manually. I realize that this would be tedious for more than 60 add-ons.
