### ISSUE TITLE
Create new search page for about:addons search

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#834]
- [ ] Create UX for search page https://github.com/mozilla/addons-frontend/issues/798/TBD
- [ ] Design the new mobile search page #798
- [x] Rename the search app to admin #805
- [ ] Implement a search component #754
- [ ] Implement a search results page #755

**Comment by tofumatt** [comment]
Okay @andymckay, here's the real tracker 😄

**Comment by tofumatt** [comment]
Surely related to https://github.com/mozilla/addons/issues/151

**Comment by muffinresearch** [comment]
Closing for now and but we should reopen when it's back on the roadmap.
